name: build and test

on:
  push:
    tags:
    - '*'
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup dotnet 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Compile solution
        run: dotnet build

      - name: Test solution
        run: dotnet test

  release:
    runs-on: windows-latest
    needs: test
    if: ${{ startsWith(github.ref, 'refs/tags/') }}

    steps:
    - name: Compile solution
      run: dotnet build -c Release